FORMAT: 1A
HOST: http://45.55.254.105/

# Weightcare

Weightcare es una API sencilla que permite a los medicos manejar sus registros clinicos de pacientesl. Esto tambien involucra ser capaz de administrar recetas medicas.

# Weightcare API Root [/]

Este recurso no contiene atributos, es solamente el punto inicial para poder
llamar a los demas recursos.

## Ver el Root [GET]

+ Response 200 (application/json)

        {}

## Group Users
Recursos relacionados con los usuarios del sistema.

## User Root [/users]
Recuperar o crear usuarios.

### Recuperar usuarios [GET]

+ Response 200 (application/json)

    + Attributes
        + id: 56 (number, fixed) - ID dentro de la base de datos
        + name: Victor (string, fixed) - Nombre de usuario
        + email: victor@gmail.com (string, fixed) - Correo de usuario
        + created_at: 130515105728 (number, fixed) - Fecha y hora de creacion del usuario
        + updated_at: 140515164929 (number, fixed) - Fecha y hora de la ultima actualizacion de usuario.

    + Body

            [
                {
                .
                .
                .
                },
                {
                    "id": 56,
                    "name": "Victor",
                    "email": "victor@gmail.com",
                    "created_at": 130515105728,
                    "updated_at": 140515164939
                },
                {
                .
                .
                .
                }
            ]

### Crear usuario [POST]

+ Request Crear usuario

            {
                "name": "Ana Guadalupe",
                "email": "ana@gmail.com",
                "password": "passwordHasheada"
            }
            
+ Response 201 (application/json)

    + Attributes
        + id: 257 (number, fixed) - ID dentro de la base de datos
        + name: Ana Guadalupe (string, fixed) - Nombre de usuario
        + email: ana@gmail.com (string, fixed) - Correo de usuario
        + created_at: 130515111012 (number, fixed) - Fecha y hora de creacion del usuario
        + updated_at: 130515111012 (number, fixed) - Fecha y hora de la ultima actualizacion de usuario.

    + Body
            
            {
                "id": 257,
                "name": "Ana Guadalupe",
                "email": "ana@gmail.com",
                "created_at": 130515111012,
                "updated_at": 130515111012
            }


## Users Operations [/users/{id}]
Operaciones para un usuario en especifico.

    + Parameters
        + id (number, optional, ´67´) ... ID del usuario a modificarse
        
### Conseguir un usuario [GET]

+ Response 200 (application/json)

    + Attributes
        + id: 67 (number, fixed) - ID dentro de la base de datos
        + name: Chuy Guerrero (string, fixed) - Nombre de usuario
        + email: chuy@gmail.com (string, fixed) - Correo de usuario
        + created_at: 130515105728 (number, fixed) - Fecha y hora de creacion del usuario
        + updated_at: 130515105728 (number, fixed) - Fecha y hora de la ultima actualizacion de usuario.
    
    + Body
        
            {
                "id": 67,
                "name": "Chuy Guerrero",
                "email": "chuy@gmail.com",
                "created_at": 130515105728,
                "updated_at": 130515105728
            }

### Actualizar un usuario [PUT]

+ Request Actualizar usuario

            {
                "name": "Jesus Guerrero",
                "email": "chuy@gmail.com",
            }
            
+ Response 200 (application/json)

    + Attributes
        + id
        
    + Body
    
            {
                "id": 67,
                "name": "Jesus Guerrero",
                "email": "chuy@gmail.com",
                "created_at": 130515105728,
                "updated_at": 160515173422
            }
            
### Borrar un usuario [DELETE]

+ Response 204 (application/json)
        

